# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-development:
     runs-on: ubuntu-latest 
     environment: development
     env :
      Az_RG_Name: RG20-Dev
     steps:
       - uses: actions/checkout@v3
       - name: Sign in to Azure
         uses: azure/login@v1
         with:
          creds:  ${{secrets.AZURE_CREDENTIALS_DEVELOPMENT}

       - name: Create RG
         uses: azure/cli@v1
         with:
           inlineScript: az group create --name ${{env.Az_RG_Name}} --location 'WestEurope'  

  deploy-prod:
     runs-on: ubuntu-latest 
     environment: production
     env :
      Az_RG_Name: RG20-PRD
     steps:
       - uses: actions/checkout@v3
       - name: Sign in to Azure
         uses: azure/login@v1
         with:
          creds:  ${{secrets.AZURE_CREDENTIALS_PRODUCTION}}

       - name: Create RG
         uses: azure/cli@v1
         with:
           inlineScript: az group create --name ${{env.Az_RG_Name}} --location 'WestEurope'
     
